### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

Yes, there is a difference in the data type of variables list_ and array_list. __list___ is a Python list object, while __array_list__ is a NumPy array object.

In [3]:
type(list_)

list

In [4]:
type(array_list)

numpy.ndarray

### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list

In [5]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

In [6]:
# Each element is string class
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [8]:
# Each element is numpy_string class
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list: 
array_list = np.array(object = list_, dtype = int)
### Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

In [9]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_, dtype = int)

In [11]:
# Each element is string class
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [13]:
# Each element is numpy_integer class
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


The first loop will print the data type of each element in list_, which will be <class 'str'>, since all the elements in list_ are strings.

The second loop will print the data type of each element in array_list, which will be <class 'numpy.int64'>, since all the elements in array_list are now integers due to the dtype=int parameter passed to the np.array() function.

### Consider the below code to answer further questions:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)
### Q4. Write a code to find the following characteristics of variable, num_array: (i) shape (ii) size

In [14]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

#### (i) shape of num_array

The shape attribute of a numpy array returns a tuple containing the dimensions of the array.

In [17]:
num_array.shape

(2, 3)

#### (ii) size of num_array

The size attribute of a NumPy array returns the total number of elements in the array.

In [16]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [21]:
a=np.zeros((3,3))

In [22]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.array([[0,0,0],[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
a.shape

(3, 3)

In [25]:
a.size

9

### Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [28]:
a=np.eye(5,5)

In [29]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
a.shape

(5, 5)

In [31]:
a.size

25